### ISSUE TITLE
Sixth Sense HUD timer?

### ISSUE THREAD

**Issue by HajimeSait0** [zenyr/PocoHud3#23]
Hey Zenyr, first suggestion/question to PocoHud3, sorry if I put it in the wrong place or formatted it wrong. :sweat_smile:

I've been curious if you were ever gonna do a Sixth Sense proc timer. I know your HUD seems more assault-oriented, so if that's the reason you haven't put one in, I understand. Just curious if you'd maybe forgotten about it, or were preoccupied, or simply didn't want to make it. Thanks for any and all replies! :relieved:

**Comment by zenyr** [comment]
More like forgotten than ignored on purpose. There are a few missing timers though.

**Comment by zenyr** [comment]
(As I stated once in a group notice before) Long time has passed and I tried a few perk timers.. And.. they were disastrously distracting since they were continuously ticking regardless of what you're doing. I was doing some major rework anyway so I need a completely new way to display some perk cooldowns.

Feature status: Postponed onto the next milestone.
